Create database configuration and docker setup
Dekriel/sharkboard pull request #3
Opened 2022-09-25 08:33 UTC by Nipa-Code

Commit includes database configuration with docker and optionally with your own host. Create `req.py` to make requests to endpoints that require database, makes testing the database easier.

2022-09-25 08:39 UTC, CaedenPH requested changes
- [ ] Without an asynchronous database wrapper, the code will block with larger requests

2022-09-25 08:39 UTC, CaedenPH commented on shark/endpoints/testing.py
> +async def test(request: Request, db):
What is `db`?

2022-09-25 08:39 UTC, CaedenPH commented on shark/endpoints/testing.py
> +    db.commit()
Should the database not be asynchronous?

2022-09-25 08:43 UTC, Nipa-Code commented on shark/endpoints/testing.py
> +async def test(request: Request, db):
thing that should not be there, should of be get rid of

2022-09-25 08:44 UTC, Nipa-Code commented on shark/endpoints/testing.py
> +    db.commit()
It can be both, if I have understood the docs at all correctly it should be asynchronous atm.

2022-09-25 10:20 UTC, CaedenPH commented
You also provide no data validation checks, ie is the author name longer than a certain length, etc.

For a robust route, you need:
  - range check
  - length check
  - type check 
  - presence check

2022-09-25 10:42 UTC, CaedenPH commented on req.py
> +# example file to make requests to the API endpoints that require DB
Move this file to a `/tests/` directory

2022-09-25 10:42 UTC, CaedenPH commented on Dockerfile
> +FROM python:3.9
Why not latest?

2022-09-25 10:42 UTC, CaedenPH commented on Dockerfile
> +RUN /usr/local/bin/python -m pip install --upgrade pip && pip install --no-cache-dir --upgrade -r requirements.txt
Why are you running `python`/`pip` from 3 different places, `/usr/local/bin/python`, `pip` and `python3`

2022-09-25 10:42 UTC, CaedenPH commented on .env_template
> +DB_URL = ""
You could just name this file `.env.template`

2022-09-25 10:42 UTC, CaedenPH commented on requirements.txt
> +requests == 2.28.1
```suggestion
```
`requests` shouldn't be a dependency, it's a dev requirement

2022-09-25 10:42 UTC, CaedenPH commented on requirements.txt
> +flake8 == 5.0.4
```suggestion
```

Dev requirement

2022-09-25 10:42 UTC, CaedenPH commented on requirements.txt
> +black == 22.8.0
```suggestion
```
Dev requirement

2022-09-25 10:42 UTC, CaedenPH commented on Dockerfile
> +COPY . .
I'm not a docker expert, what does this do?

2022-09-25 10:42 UTC, CaedenPH commented on shark/constants.py
> +    VERSION: str = "0.1"
```suggestion
```

All these 'constants' should go in the `__init__.py` as dunders; 
`__version__ = "0.2"` - you may also want to increment the version

2022-09-25 10:42 UTC, CaedenPH commented on shark/endpoints/testing.py
> +from shark.utils.database import engine
```suggestion
from .utils import models, schemas
from .utils.crud import get_db
from .utils.database import engine
```

These should be relative imports.

`utils` dif should also have an `__init__` importing relative functions/classes

2022-09-25 10:46 UTC, Nipa-Code commented on Dockerfile
> +FROM python:3.9
it's copied from my other API so I haven't cared yet to update all the values, eg. the DB is still using version (12?) aand the newest is 14 or 15. but it works

2022-09-25 10:47 UTC, Nipa-Code commented on requirements.txt
> +requests == 2.28.1
it will have use, assuming we are not going to use standard libs in the future

2022-09-25 10:47 UTC, Nipa-Code commented on requirements.txt
> +flake8 == 5.0.4
will be used for testing in the future (probably)

2022-09-25 10:48 UTC, Nipa-Code commented on requirements.txt
> +black == 22.8.0
will be used for testing in the future (probably)

2022-09-25 10:49 UTC, Nipa-Code commented on shark/constants.py
> +    VERSION: str = "0.1"
Every PR = new version? never really used `version` stuff before

2022-09-25 10:51 UTC, CaedenPH commented on Dockerfile
> +FROM python:3.9
Okay

2022-09-25 10:54 UTC, Nipa-Code commented on Dockerfile
> +RUN /usr/local/bin/python -m pip install --upgrade pip && pip install --no-cache-dir --upgrade -r requirements.txt
if it works, don't touch it

2022-09-26 16:46 UTC, CaedenPH approved these changes

2022-09-26 17:34 UTC, merged